import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import Image from 'next/image'
import bgPicture from '../public/images/loft.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Image
        src={bgPicture}
        width={144}
        height={144}
        alt="Your Name"
      />
      <Head>
        <title>Loft Furniture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1 className="title">
  Read{' '}
  <Link href="/posts/first-post">
    <a>this page!</a>
  </Link>
</h1>

      <footer className={styles.footer}>
             </footer>
    </div>
  )
}
